uint8 POSITION=1
uint8 ORIENTATION=2
uint8 LINEAR_VELOCITY=4
uint8 ANGULAR_VELOCITY=8
uint8 LINEAR_ACCELERATION=16
uint8 ANGULAR_ACCELERATION=32
uint8 ALL=63

uint8 valid_fields
geometry_msgs/Point position
geometry_msgs/Quaternion orientation
geometry_msgs/Vector3 linear_velocity
geometry_msgs/Vector3 angular_velocity
geometry_msgs/Vector3 linear_acceleration
geometry_msgs/Vector3 angular_acceleration
